spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        input:
          binder: kafka
          destination: test-topic
          content-type: text/plain
          group: input-group-1
          consumer:
            maxAttempts: 1
            backOffInitialInterval : 10000 # 10seconds
            backOffMaxInterval : 100000    # 100 seconds
            backoffMultiplier : 2.0       # retries will be done after 10 20 40 80 seconds. The total is 150 which is within the default max retry interval
        output:
          binder: kafka
          destination: dlq-topic
          group: output-group-1
          content-type: text/plain