spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        input:
          binder: kafka
          destination: test-topic
          content-type: text/plain
          group: group1
          consumer:
            # https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/3.0.6.RELEASE/reference/html/spring-cloud-stream-binder-kafka.html#kafka-consumer-properties
            maxAttempts: 1
            backOffInitialInterval: 5000  # 5 seconds
            backOffMaxInterval: 100000    # 100 seconds
            backoffMultiplier: 2.0        # retries will be done after 5 10 15 20